version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-development
    image: fe/navigation:dev
    container_name: navigation-development
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app/
    environment:
     NODE_ENV: development
