version: '3'
services:
  web:
    build: .
    image: fe/navigation:v1.0
    container_name: navigation-production
    ports:
    - "80:8080"
    volumes:
    - .:/usr/src/app/
    environment:
     NODE_ENV: production
