FROM node:6.10.3
LABEL "raso navigation"

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app
RUN npm install
COPY . /usr/src/app

ENV NODE_ENV development

EXPOSE 3000
CMD ["npm", "start"]
